import pandas as pd
from src.config.labels import ITEM_LABEL, TITLE_LABEL, GENRES_LABEL, BIAS_VALUE_LABEL


class Item:
    """
        Data holder for our item.

        Parameters
        ----------
        id : int

        title : str

        genre : dict[str, float]
            The item/movie's genre distribution, where the key
            represents the genre and value corresponds to the
            ratio of that genre.

        score : float
            Score for the item, potentially generated by some
            recommendation algorithm.
        """

    def __init__(self, _id, title, genres, bias, score=None):
        self.id = _id
        self.title = title
        self.score = score
        self.genres = genres
        self.bias = bias

    # def __repr__(self):
    #     return self.title


def create_item_mapping(df_item, bias_df):
    """Create a dictionary of item id to Item lookup."""
    item_bias_df = pd.merge(
        df_item, bias_df,
        how='inner', left_on=ITEM_LABEL, right_on=ITEM_LABEL
    )
    item_mapping = dict()
    for row in item_bias_df.itertuples():
        item_id = getattr(row, ITEM_LABEL)
        item_title = getattr(row, TITLE_LABEL)
        item_genre = getattr(row, GENRES_LABEL)
        item_bias = getattr(row, BIAS_VALUE_LABEL)

        splitted = item_genre.split('|')
        genre_ratio = 1. / len(splitted)
        item_genre = {genre: genre_ratio for genre in splitted}

        item = Item(item_id, item_title, item_genre, item_bias)
        item_mapping[item_id] = item

    return item_mapping
